import { describe, expect, it } from 'vitest';
import { parseSections, stripMarkdown } from './changelog';

describe('parseSections', () => {
  it('groups bullet items under the heading above them', () => {
    const sections = parseSections(['### Features', '- adds a widget', '- adds a setting'].join('\n'));

    expect(sections).toEqual([{ heading: 'Features', items: ['adds a widget', 'adds a setting'] }]);
  });

  it('keeps separate headings in separate sections', () => {
    const sections = parseSections(
      ['### Features', '- a feature', '### Fixes', '- a fix'].join('\n'),
    );

    expect(sections).toEqual([
      { heading: 'Features', items: ['a feature'] },
      { heading: 'Fixes', items: ['a fix'] },
    ]);
  });

  it('collects bullets that appear before any heading into an unnamed section', () => {
    const sections = parseSections(['- a loose item', '- another'].join('\n'));

    expect(sections).toEqual([{ heading: '', items: ['a loose item', 'another'] }]);
  });

  it('accepts asterisk bullets as well as dashes', () => {
    const sections = parseSections(['## Notes', '* starred item'].join('\n'));

    expect(sections).toEqual([{ heading: 'Notes', items: ['starred item'] }]);
  });

  it('ignores blank lines', () => {
    const sections = parseSections(['### Features', '', '- a feature', ''].join('\n'));

    expect(sections).toEqual([{ heading: 'Features', items: ['a feature'] }]);
  });

  it('returns nothing for an empty changelog', () => {
    expect(parseSections('')).toEqual([]);
  });
});

describe('stripMarkdown', () => {
  it('keeps the text of a markdown link and drops the target', () => {
    expect(stripMarkdown('adds [the widget](https://example.com)')).toBe('adds the widget');
  });

  it('removes the trailing commit reference generated by the changelog tool', () => {
    expect(stripMarkdown('adds a widget ([a1b2c3d](https://github.com/x/y/commit/a1b2c3d))')).toBe(
      'adds a widget',
    );
  });

  it('drops bold markers so the scope prefix reads as text', () => {
    expect(stripMarkdown('**extension:** add tabs in popup')).toBe('extension: add tabs in popup');
  });

  it('leaves plain text untouched', () => {
    expect(stripMarkdown('just a plain entry')).toBe('just a plain entry');
  });
});
